pipeline {
    agent any

    environment {
        // Secrets store se API Key utha rahe hain
        SECRET_TOKEN = credentials('MY_API_KEY')
    }

    stages {
        stage('Test Credentials Injection') {
            steps {
                echo '🚀 Injecting secret into python app...'
                sh "API_KEY=${env.SECRET_TOKEN} python3 Docker-secret/app.py"
            }
        }
    }
}